# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Verify SonarCloud Quality Gate Result"
      $QualityGateResult = Invoke-RestMethod -Method Get -Uri "https://sonarcloud.io/api/qualitygates/project_status?projectKey=ura-backend"
      
      $QualityGateResult | ConvertTo-Json | Write-Host
        
      if ($QualityGateResult.projectStatus.status -eq "OK"){
          Write-Host "Quality Gate Succeeded"
      }
      else{
          throw "Quality gate failed. Please check and fix the issues by reviewing the same."
      }