apidetails:
  title: URA Car Parking API
  description:  URA Car Parking API
  version: 1.0
  terms-of-service: Terms of Service
  name: HCL Developers
  url: https://www.hcl.com/in/
  email: developers@hcl.com
  license: Apache License Version 2.0
  licenseUrl: https://www.apache.org/licesen.html
spring:
  datasource:
    url: jdbc:sqlserver://ura-sql.database.windows.net:1433;databaseName=ura-db
    username: uradbadmin
    password: 9o0T%KRDs!
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:      ddl-auto: update
logging:
  level: 
    org: 
      hibernate:
        SQL: DEBUG
        type: 
          descriptor: 
            sql: 
              BasicBinder: TRACE
      
msg:
    userstatus: 
      pending: User account is not activated yet, once activated we will process the ticket request
      error: User has pedning issues, please resolve the same before raising parking ticket request
    parking:
      notavilable: Parking is not available for the selected vehicle 
    ticket:
      approved: Parking ticket is now approved
     