apidetails:
  title: URA Car Parking API
  description:  URA Car Parking API
  version: 1.0
  terms-of-service: Terms of Service
  name: HCL Developers
  url: https://www.hcl.com/in/
  email: developers@hcl.com
  license: Apache License Version 2.0
  licenseUrl: https://www.apache.org/licesen.html
spring:
  jpa:
    hibernate:      ddl-auto: update
logging:
  level: 
    org: 
      hibernate:
        SQL: DEBUG
        type: 
          descriptor: 
            sql: 
              BasicBinder: TRACE
azure:
  keyvault:
    client-id: a4f2fedc-a603-4bd4-b483-29ed224e3776
    client-key: 93M9_yE59rY2NdWd.n2mXnvd_A6.9.VVq1
    enabled: true
    tenant-id: 189de737-c93a-4f5a-8b68-6f4ca9941912
    uri: https://ura-keyvalult.vault.azure.net/      
msg:
    userstatus: 
      pending: User account is not activated yet, once activated we will process the ticket request
      error: User has pedning issues, please resolve the same before raising parking ticket request
    parking:
      notavilable: Parking is not available for the selected vehicle 
    ticket:
      approved: Parking ticket is now approved
